apiVersion: v1
kind: Namespace
metadata:
  name: my-nginx-evlkwf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-evlkwf
  namespace: my-nginx-evlkwf
  labels:
    name: nginx-evlkwf
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-evlkwf
  template:
    metadata:
      namespace: my-nginx-evlkwf
      labels:
        name: nginx-evlkwf
    spec:
      containers:
      - name: nginx-evlkwf
        image: nginx
        ports:
        - containerPort: 80

